a = float(input('Enter a number: '))
b = float(input('Enter outher number: '))
print('The sum is {:.2f}' .format(a + b))
print('The subtraction is {:.2f}' .format(a - b))
print('The multiplication is {:.2f}' .format(a * b))
print('The division is {:.2f}' .format(a / b))
print('The integer division is {:.2f}' .format(a // b))
print('The remainder division is {:.2f}' .format(a % b))
print('The potentiation is {:.2f}' .format(a ** b))