a = float(input('Enter a number: '))
b = float(input('Enter outher number: '))
print('The sum is {}' .format(a + b))
print('The subtraction is {}' .format(a - b))
print('The multiplication is {}' .format(a * b))
print('The division is {}' .format(a / b))
print('The potentiation is {}' .format(a ** b))
print('The integer division is {}' .format(a // b))
print('The remainder division is {}' .format(a % b))
